### ISSUE TITLE
Base64 signature

### ISSUE THREAD

**Issue by akegalj** [menelaos/purescript-b64#2]
Based on wiki https://en.wikipedia.org/wiki/Base64 , base64 should be:
```
encode :: Uint8Array -> String
decode :: String -> Uint8Array
```
Its much more clear this way then implicitly using utf8 or some other encoding.

Simple implementation that can be wrapped is https://www.npmjs.com/package/base64-js

**Comment by menelaos** [comment]
I've added functions that work on `Uint8Array` under `Data.Binary.Base64` (https://github.com/menelaos/purescript-b64/commit/800d62466cab5b47da6d01667b0862ad1e2021f2).

**Comment by akegalj** [comment]
@menelaos thanks <3
