### ISSUE TITLE
Update for PureScript 0.12.0

### ISSUE THREAD

**Issue by menelaos** [menelaos/purescript-b64#4]
Currently held up by https://github.com/jutaro/purescript-typedarray/pull/8

**Comment by newlandsvalley** [comment]
@jutaro has merged the PR but has not (yet) made a release.  However, I've just noticed that he has said in this last commit that he is looking for another maintainer for his PureScript packages. I wondered if you fancied offering to take it over, given that it is such a fit to your own libraries?

Incidentally, many thanks for b64.

**Comment by menelaos** [comment]
Thanks for the notification! I've opened an issue here: https://github.com/jutaro/purescript-typedarray/issues/9

**Comment by menelaos** [comment]
In order to speed up the release of a new version, I've decided to drop the dependency on `purescript-typedarray` for now.

**Comment by newlandsvalley** [comment]
Many thanks.  I think this is sensible given the circumstances - exactly what I did in my fork.
